# Generated by Django 2.2.2 on 2019-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gid',
            field=models.IntegerField(default=0),
        ),
    ]
