# Generated by Django 2.2.2 on 2019-10-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
