# Generated by Django 2.2.2 on 2019-09-13 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='g_id',
        ),
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, upload_to=uploads.models.content_file_name),
        ),
        migrations.AddField(
            model_name='file',
            name='images',
            field=models.ImageField(blank=True, upload_to='album'),
        ),
        migrations.AddField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 16, 3, 16, 837352, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='file',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 16, 3, 16, 837324, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='folder',
            name='children',
            field=models.ManyToManyField(related_name='_folder_children_+', to='uploads.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='uploads.Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to='accounts.Profile'),
        ),
    ]
