# Generated by Django 2.2.2 on 2019-08-31 23:16

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, default='', upload_to=uploads.models.content_file_name),
        ),
    ]
