# Generated by Django 2.2.2 on 2019-10-01 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20191001_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 22, 56, 42, 290313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 22, 56, 42, 290272, tzinfo=utc)),
        ),
    ]
