# Generated by Django 2.2.2 on 2019-09-28 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20190927_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 22, 41, 55, 349701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 22, 41, 55, 349679, tzinfo=utc)),
        ),
    ]
