# Generated by Django 2.2.2 on 2019-09-28 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20190928_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 23, 50, 32, 262541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 23, 50, 32, 262511, tzinfo=utc)),
        ),
    ]
