# Generated by Django 2.2.2 on 2019-08-31 23:50

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20190831_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(blank=True, upload_to=uploads.models.content_file_name),
        ),
    ]
