# Generated by Django 2.2.2 on 2019-10-01 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20191001_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 22, 56, 56, 67593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 22, 56, 56, 67568, tzinfo=utc)),
        ),
    ]
