# Generated by Django 2.2.2 on 2019-09-13 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20190913_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='gid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='uploads.Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 16, 7, 54, 451146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 16, 7, 54, 451124, tzinfo=utc)),
        ),
    ]
