# Generated by Django 2.2.2 on 2019-08-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20190831_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='images',
            field=models.ImageField(blank=True, upload_to='album'),
        ),
    ]
