# Generated by Django 2.2.2 on 2019-10-01 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20191001_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 23, 6, 45, 254183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 23, 6, 45, 254157, tzinfo=utc)),
        ),
    ]
