# Generated by Django 2.2.2 on 2019-10-05 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_auto_20191001_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 1, 26, 1, 494414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 1, 26, 1, 494392, tzinfo=utc)),
        ),
    ]
