# Generated by Django 2.2.2 on 2019-09-16 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20190916_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='folderfiles',
            field=models.ManyToManyField(related_name='folderfiles', to='uploads.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 0, 40, 19, 599387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 0, 40, 19, 599366, tzinfo=utc)),
        ),
    ]
